// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVU95PlFJGeS113fi6-m4vgvNRFQzv_kg',
    appId: '1:297966099397:android:1666aeccca6a58ec3709ac',
    messagingSenderId: '297966099397',
    projectId: 'demologinoffice',
    storageBucket: 'demologinoffice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAyU6Prf5nl3nbCI8HdgM50_B_kEH5AWU',
    appId: '1:297966099397:ios:d499e0c185462cdb3709ac',
    messagingSenderId: '297966099397',
    projectId: 'demologinoffice',
    storageBucket: 'demologinoffice.appspot.com',
    androidClientId: '297966099397-ajpuc1kling8n1qs46eeo8n1b7sghl4m.apps.googleusercontent.com',
    iosClientId: '297966099397-uho7fsecs08o9qqh7s6cdtojdljifvmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoLoginOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAyU6Prf5nl3nbCI8HdgM50_B_kEH5AWU',
    appId: '1:297966099397:ios:d499e0c185462cdb3709ac',
    messagingSenderId: '297966099397',
    projectId: 'demologinoffice',
    storageBucket: 'demologinoffice.appspot.com',
    androidClientId: '297966099397-ajpuc1kling8n1qs46eeo8n1b7sghl4m.apps.googleusercontent.com',
    iosClientId: '297966099397-uho7fsecs08o9qqh7s6cdtojdljifvmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoLoginOffice',
  );
}
